name: Sync Fork

on:
  schedule:
    - cron: '*/30 * * * *' # 每6小时运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: MoonTechLab                            # 上游仓库的拥有者
          repo: LunaTV                                # 上游仓库的名称
          base: main                      # 上游仓库的基础分支
          head: main                      # 你的 fork 仓库的头部分支
          token: ${{ secrets.PERSONAL_TOKEN }} # 必须使用具有 repo/public_repo 权限的 PAT
